spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        generate_statistics: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  messages:
    basename: validation

logging:
  level:
    org:
      hibernate: INFO